<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ca814979-55fc-4f26-a355-e28ac3ae8616</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Google.Apis.Auth.AspNetCore3" Version="1.69.0" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.69.0.3703" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.0" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.14">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Demo.BLL\Demo.BLL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
    <Folder Include="Mapping\Profiles\Employee\" />
    <Folder Include="Models\" />
    <Folder Include="wwwroot\Files\Images\" />
    <Folder Include="wwwroot\images\" />
    <Folder Include="wwwroot\js\" />
    <Folder Include="wwwroot\lib\bootstrap\" />
    <Folder Include="wwwroot\lib\bootstrap\dist\js\" />
    <Folder Include="wwwroot\lib\jquery-validation-unobtrusive\" />
    <Folder Include="wwwroot\lib\jquery-validation\" />
    <Folder Include="wwwroot\lib\jquery-validation\dist\" />
    <Folder Include="wwwroot\lib\jquery\" />
    <Folder Include="wwwroot\lib\jquery\dist\" />
  </ItemGroup>

</Project>
